### PR TITLE
✨ Add Album to Rich Presences' Large Picture

### PR DESCRIPTION
**Pull request by Alipoodle**
Discord has finally added support of being able to use Custom Links within Rich Presences allowing for us to be able to display the Album Art of the current song in the Large image!
A Long awaited feature implemented. 😍

Large Profile:
Large Profile

Small profile:
Small Profile

### CODE REVIEW

**Review by reHamad — COMMENTED** [review]
how can I apply this?

**Comment by Alipoodle** [comment]
Simple answer: You wait until a new build is created for the nightly or code is pushed to stable.

Complex answer: You build and make the application yourself from the development build.

**Comment by reHamad** [comment]
> Simple answer: You wait until a new build is created for the nightly or code is pushed to stable.
> 
> Complex answer: You build and make the application yourself from the development build.

When is it getting released?

**Comment by Alipoodle** [comment]
I plan to do a Release soon once I've finished work on the most recent PR for some API changes. 😁

**Comment by Adam-Kay** [comment]
> I plan to do a Release soon once I've finished work on the most recent PR for some API changes. 😁

Looking forward to this!
I've been exploring this app all throughout today and in my opinion this is the only thing that is missing for me. Thank you for your continuous improvement!

**Pull request merged**
