### PR TITLE
Scrobble albums

### PR DESCRIPTION
**Pull request by chaoky**
Use unpublished fork of scribble that correctly scrobbles albums
The only downside to this is that the git repo may be deleted at any moment (very unlikely to happen).

https://github.com/dittodhole/node-scribble-js/tree/a2b37f585c5382863319115db36201399477ed43

### CODE REVIEW

**Comment by chaoky** [comment]
#427 #426

**Comment by chaoky** [comment]
#426 #120

**Comment by rickinbsb** [comment]
thank you for this!
can you change it to target the development branch?

**Comment by adlerluiz** [comment]
> Use unpublished fork of scribble that correctly scrobbles albums
> The only downside to this is that the git repo may be deleted at any moment (very unlikely to happen).
> 
> https://github.com/dittodhole/node-scribble-js/tree/a2b37f585c5382863319115db36201399477ed43

I did the fork to keep it in case something happens

**Comment by G4Zz0L1** [comment]
Any news on this?

**Comment by G4Zz0L1** [comment]
I'm on Arch, with the aur package. No problem, I'll wait until it comes here. I should have read the merge before my previous comment before posting, my fault.

**Comment by rickinbsb** [comment]
ytmdesktop-git builds from the development branch, you can use that one to
have it earlier

Em ter, 13 de out de 2020 20:47, G4Zz0L1 <notifications@github.com>
escreveu:

**Comment by Thalarion** [comment]
Is there a new Windows release with this fix somewhere on the horizon? My last.fm library has been filling up with tracks missing album name for some time now, which is quite unfortunate.

Or perhaps a Windows build of the development branch?

**Comment by chaoky** [comment]
just download the source code
download nodejs
type `npm i`
wait
type `npm run build:win`
wait
click on dist/win-unpacked/YouTube Music Desktop App.exe

**Comment by Thalarion** [comment]
Thanks, that is easier than I thought. Only, I used `yarn` instead, out of habit.

I did not have the **Desktop development with C++** workload so it failed with `gyp ERR! stack Error: Could not find any Visual Studio installation to use`.

So I installed it (along with the latest Visual Studio Community; I only had bare bones Visual Studio Code), the same error showed up again, but everything worked instead. Very weird.

The installer works fine as well and YTMDP is scrobbling albums now! Which is nice.

**Comment by rickinbsb** [comment]
that error only prevents the windows media service integration from working, but everything else should be fine

**Comment by Thalarion** [comment]
> 
> 
> that error only prevents the windows media service integration from working, but everything else should be fine

Right, that's exactly what happened. Is this a known bug or can it be fixed somehow? The relevant workload cannot be more installed than it already is...

By the way, it seems it's YouTube giving the scrobblers same thing in Artist and Album Artist, which is not nice.

**Pull request merged**
