### PR TITLE
Icon redesign and pixelization fix

### PR DESCRIPTION
**Pull request by asuetin**
I've redesigned the app icon and fixed the pixelization on Windows  #108. The only place where it remains pixelated is the search results in the Start Menu, but that seems to be a Windows issue as it mangles every icon that appears there.

### CODE REVIEW

**Comment by rickinbsb** [comment]
for reference, this is the current icon next to the proposed one:
image
image

**Comment by adlerluiz** [comment]
Great, it was very good, could you do only the Background and the foreground? I will add in the app

**Comment by adlerluiz** [comment]
This is great! can you provide the background and the arrow as separate svgs? I'll use them on the rc app

**Comment by adlerluiz** [comment]
what do you think @rickinbsb ?

**Comment by rickinbsb** [comment]
I dig it! It might be a little too pinkish, but I can get used to these colors

**Comment by adlerluiz** [comment]
right, the app icon looks like this

app_icon_remote_adaptive

**Comment by asuetin** [comment]
> This is great! can you and make it a little more red and provide the background and the arrow as separate pngs? I'll use them on the rc app
Sure, here are [all the raw assets I used.](https://1drv.ms/u/s!ArbKaOQedFN6kKJD19g2DMSZIuKLyA?e=v7SOr2)

I included separate pngs/svgs for the background and arrow as well as a redder version of the icon. However, if you ask me, I vote for the pinkish one. I've always found Google's insistence on using the eye-searing pure red for everything YouTube a bit annoying :P

**Comment by rickinbsb** [comment]
yea, it's just a matter of getting used to it, I do like it, great job!

**Comment by adlerluiz** [comment]
Wow, the _redder is perfect =D

**Comment by rickinbsb** [comment]
I vote for the first version too (not the redder)

**Comment by rickinbsb** [comment]
but one more request, if that's ok, can you send us the background without the circle crop? as in the whole image being filled, without borders. This is necessary to use adaptative icons

**Comment by rickinbsb** [comment]
just wanted to point out that the new icon really fits with papirus icons

**Comment by asuetin** [comment]
> but one more request, if that's ok, can you send us the background without the circle crop? as in the whole image being filled, without borders. This is necessary to use adaptative icons

Added it to the shared folder (icon_512_bg.svg and icon_512_bg.png).

**Comment by adlerluiz** [comment]
already modified in the discord

**Comment by rickinbsb** [comment]
@asuetin oh, sorry, I meant the full square

**Comment by asuetin** [comment]
> @asuetin oh, sorry, I meant the full square
> edit: this is why: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

Added the square version (icon_512_square_bg.svg and icon_512_square_bg.png).

**Pull request merged**
