### PR TITLE
Add localization. Update Readme.md. Reorder files.

### PR DESCRIPTION
**Pull request by snxx-lppxx**
## Description of Changes:
- Reorder html/css files;
- Add localization (Kazakhstan);
- Update Readme.md.

## Checklist
- [x] My code follows the [Contribution Guide](https://github.com/ytmdesktop/ytmdesktop#to-contribute)

### CODE REVIEW

**Comment by mingjun97** [comment]
Nice job! Thanks for your contribution!

**Review by mingjun97 — CHANGES_REQUESTED** [review]
Add an option for your language here, otherwise it is not visible for users. :)

https://github.com/ytmdesktop/ytmdesktop/blob/c60821dbbc178fbea0b60363b0e267d619054cd8/src/pages/settings/settings.html#L184

**Comment by snxx-lppxx** [comment]
Hi @mingjun97! Please review this.

**Comment by snxx-lppxx** [comment]
Hi @mingjun97, thanks!

**Pull request merged**
