### PR TITLE
Update brew install command

### PR DESCRIPTION
**Pull request by abelland**
removed cask directive

### CODE REVIEW

**Comment by adlerluiz** [comment]
I'm not familiar with the mac, with or without cask, can I install it?

**Comment by abelland** [comment]
`brew cask install` has been removed in favour of `brew install --cask` or even better `brew install` directly

Running `brew cask install ytmdesktop-youtube-music` copy and pasted from the Readme ends up with an error right now

**Comment by rickinbsb** [comment]
can you change this to target the development branch?

**Comment by rickinbsb** [comment]
relevante changelog: https://brew.sh/2020/12/01/homebrew-2.6.0/#:~:text=All%20brew%20cask%20commands%20have,Homebrew.

**Pull request merged**
