### PR TITLE
Added button for enable disable global shortcut

### PR DESCRIPTION
**Pull request by khisby**
# Description
add button to enable/disable global shortcut.

# Context Background
when I use YTM Dekstop, I often press the wrong button that triggers the shortcut, and it's very annoying

# Support locales
"MEDIA_CONTROL_ENABLE_DISABLE": "Enable/Disable Shortcut Media Control",
https://github.com/ytmdesktop/ytmdesktop-locales/pull/23

# Screenshot Result
image
image

# How Has This Been Tested
i tested the local dev build and checked the shortcut work as expected

### CODE REVIEW

**Comment by Alipoodle** [comment]
I don't see why this is needed when each individual keybind can be disabled?
and in turn can be done on every command.

We plan to remove all default keybinds in a future up due to this issue and it causing issues.
#912 has more details.

image

Example I only have the Volume on/off.
image

**Comment by khisby** [comment]
> I don't see why this is needed when each individual keybind can be disabled? and in turn can be done on every command.
> 
> We plan to remove all default keybinds in a future up due to this issue and it causing issues. #912 has more details.
> 
> image
> 
> Example I only have the Volume on/off. image

I think it will be very easy if we can disable all shortcuts with just one button and without removing the previous key binding configuration.

Ithink it's not right to remove the default keybinds. you can remap default keybinds or **you can use this my PR and set it to default turn off and user can turn on if they needed**.

and the issue https://github.com/ytmdesktop/ytmdesktop/issues/912 can be solve.

**Comment by khisby** [comment]
Hi @Alipoodle i've add some commit to fix shortcut issue and it to make sure work as expected

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2

**Pull request closed without merging**
