### PR TITLE
:sparkles: Added media control on dock icon

### PR DESCRIPTION
**Pull request by 2gn**
image

resolving this issue: https://github.com/ytmdesktop/ytmdesktop/issues/948

### CODE REVIEW

**Comment by 2gn** [comment]
dmg file for beta-testing can be downloaded from [here](https://github.com/2gn/ytmdesktop/releases/download/v1.14.2-alpha-UNOFFICIAL/YouTube.Music.Desktop.App-1.14.2.dmg) if you have any MacOS device.

**Comment by Alipoodle** [comment]
Why close this?

**Comment by 2gn** [comment]
> Why close this?

There's no special reason.

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2

**Pull request closed without merging**
