### PR TITLE
Add basic mpris support

### PR DESCRIPTION
**Pull request by RodrigoLeiteF**
This PR intends to add basic MPRIS functionality to the project. It allows for easier integration of the program with other programs that might benefit from knowing it's information.

https://specifications.freedesktop.org/mpris-spec/2.2/

### CODE REVIEW

**Comment by adlerluiz** [comment]
Thank you very much for your PR, this integration will help the player a lot

**Comment by adlerluiz** [comment]
@RodrigoLeiteF 

I'm trying to start in my environment, but I always got this message, was there any configuration missing?

App threw an error during load
Error: could not get DISPLAY environment variable to get dbus address

**Comment by RodrigoLeiteF** [comment]
> @RodrigoLeiteF
> 
> I'm trying to start in my environment, but I always got this message, was there any configuration missing?
> 
> App threw an error during load
> Error: could not get DISPLAY environment variable to get dbus address

That's odd. Is your DISPLAY environment variable set? If not, try setting it to ":0" and see if it works.

**Comment by adlerluiz** [comment]
I use windows and I have 2 monitors, I will disable one to see if it still occurs

**Comment by adlerluiz** [comment]
nothing...

**Comment by RodrigoLeiteF** [comment]
As far as I know Windows doesn't have DBus support, so it's expected that it wouldn't work :)

**Comment by adlerluiz** [comment]
It will be necessary to create an OS validation, this error prevents the application from starting

**Comment by RodrigoLeiteF** [comment]
Gotcha. I'll add that asap :)

**Comment by adlerluiz** [comment]
Thank you =D

**Pull request merged**
