### PR TITLE
✨ macOS Media Integration (with package.json fix)

### PR DESCRIPTION
**Pull request by dm3ch**
I would really love to see https://github.com/ytmdesktop/ytmdesktop/pull/637 merged, so I have created new PR with this changes where I have added package.json fixes proposed during review of original PR

### CODE REVIEW

**Comment by dm3ch** [comment]
Ran `yarn run` to make CI jobs successful. It upgraded electron version, I can drop this changes if they are not desirable in development branch

**Comment by dm3ch** [comment]
@mingjun97 FYI

**Comment by dm3ch** [comment]
This integration is based on https://github.com/MarshallOfSound/electron-media-service library. Which is also multiplatform.

Please inform me if you are OK (going to merge) this PR. If it's so I would rebase it

**Comment by dm3ch** [comment]
I just looked on Xsms and I believe it could be very cool solution to split media platform specific things from main database. Also I love rust lang a lot.

But I just tried to research how difficult it would be to integrate macos support to Xosms and it seems it's completely not a low hanging fruit. To be honest it seems it would require to reimplement ObjC interface for some parts of macos media library. And it seems that there's no good tutorials how to do that for now. :(

**Comment by NovusTheory** [comment]
> 
> 
> I just looked on Xsms and I believe it could be very cool solution to split media platform specific things from main database. Also I love rust lang a lot.
> 
> But I just tried to research how difficult it would be to integrate macos support to Xosms and it seems it's completely not a low hanging fruit. To be honest it seems it would require to reimplement ObjC interface for some parts of macos media library. And it seems that there's no good tutorials how to do that for now. :(

Unfortunately that is very true, and I've already messed with doing it and have access to the API needed to make it, but it simply doesn't work and there's too much debugging work that is needed especially when I don't specifically own a mac to constantly develop on. So I might wrap this up and say we'll implement this PR because Xosms seems far fetched from doing it in a timely manner.

**Comment by dm3ch** [comment]
@NovusTheory 
Am I right understand that it means that it's a good idea to resolve conflicts?

Could you please share what you have for macos in separate branch? Maybe I would be able to take a look, later.

**Comment by NovusTheory** [comment]
> Am I right understand that it means that it's a good idea to resolve conflicts?
Yup

> Could you please share what you have for macos in separate branch? Maybe I would be able to take a look, later.
https://github.com/NovusTheory/xosms/tree/macos-support

**Comment by dm3ch** [comment]
> > Am I right understand that it means that it's a good idea to resolve conflicts?
> 
> Yup
> 
> > Could you please share what you have for macos in separate branch? Maybe I would be able to take a look, later.
> 
> https://github.com/NovusTheory/xosms/tree/macos-support

TY. I would try to find what's the problems with xosms on macos. I have spent some time desiring to play with Rust and it seems the time has come.

Just merged developed to my branch, to resolve merge conflicts

**Comment by dm3ch** [comment]
Maybe we can merge at least this PR to make media controls working on MacOS.
Unfortunately, now xosms PR is closed

**Comment by cvakiitho** [comment]
So is anything blocking this merge, more testing needed?

**Comment by victor-roswell** [comment]
Following up for an answer to @cvakiitho's comment. 
I would love to contribute to get this resolved.

**Pull request merged**
