### PR TITLE
Add buttons to Discord rich presence

### PR DESCRIPTION
**Pull request by NovusTheory**
While currently undocumented (which implicitly means unsupported). Discord has added a new feature to activities called buttons. This pull request adds "Play on YouTube Music" to the rich presence. It links to the url of the song currently playing.

I would like to request this PR stays active and not immediately closed out awaiting Discord to confirm and document buttons. The [PR for this is here](https://github.com/discord/discord-api-docs/pull/2219).

A note that was added in the code is the usage of `request()` instead of `setActivity()`. The reason is because the discord-rpc library was updated on master to support buttons but an update has not been deployed to npm with it.

### CODE REVIEW

**Comment by NovusTheory** [comment]
Note: Merge conflict resolved with #621

**Comment by mingjun97** [comment]
Is this PR ready to merge? Since I see that you say we are waiting Discord confirm and document the buttons. :)

**Comment by NovusTheory** [comment]
> 
> 
> Is this PR ready to merge? Since I see that you say we are waiting Discord confirm and document the buttons. :)

Discord hasn't merged buttons documentation yet so no

**Comment by NovusTheory** [comment]
Documentation has been merged, you are free to merge this PR @mingjun97

**Pull request merged**
