### PR TITLE
:bug: fix hang on npx

### PR DESCRIPTION
**Pull request by SomeAspy**
I wasn't able to build this (I still can't, but it won't hang with this fix) and found it kept hanging on the npx command. following https://github.com/electron-userland/electron-builder/issues/6411 I replaced npx npm exec.

### CODE REVIEW

**Comment by Alipoodle** [comment]
Some work is going to need to be done regarding fixing our actions with this PR.
Build process is currently using NPM 6 which causes this to fail as `npm exec` is a npm 7 release...

I wanna do some investigation.
Can I ask why you've deleted this so soon?

**Comment by SomeAspy** [comment]
Sorry I saw the fail, and realized it didn't work

**Comment by Alipoodle** [comment]
There's a few reasons why this could hang for you.
I'm assuming you are running Windows 10/11.
You need Visual Studio 2015 installed for the NodeRT libraries to compile correctly as they are hard coded to this version of Visual Studio. We want to entirely remove these but currently we're waiting on another library to be ready to be installed and for it to work a lot better.
Otherwise that is the main issue I have found regarding installing for people.

**Comment by SomeAspy** [comment]
I tried building it using npm, pnpm, and yarn, on wsl and windows 11 I has VS 2017 and 2022 installed so let me try 2015

**Comment by SomeAspy** [comment]
@Alipoodle I installed vs 2015 and I still have the issue where it freezes

**Comment by SomeAspy** [comment]
nevermind, I got it, thanks!

**Pull request closed without merging**
