### PR TITLE
Remove user agent, allows Google Sign In with 2FA

### PR DESCRIPTION
**Pull request by joser93**
Greetings

I just saw this project on a video and find out about this issue https://github.com/ytmdesktop/ytmdesktop/issues/866. 

As far as I see, the user agent is something that you want to keep, but I don't see why, so, I tested to remove it at all, Also I tested with 1.13 but I am not submitting a PR of that just to avoid merge conflicts in the future or maybe a 1.13.1 branch and release for this fix.

Anyway, I tested this, used npm start and I am able to log in, the 2FA will ask for a hardware key, but at the bottom of that, there's another option to choose your desired verification process, choose what you can use and sign in. 

I also saw on the issue that changing this might causes some troubles, but, with 1.13, I was not able to spot a problem, playback, shortcuts, lyrics, sysicon tray, all seems to works fine. Although, testing 1.14 (master) I encounter other issues that are not related with this change, maybe I'll post about it later. If there's something else that I must test or contribute something else to fix this, I'll keep in touch.

I hope this helps and brings back on track YTM development.

### CODE REVIEW

**Comment by Alipoodle** [comment]
This feels like a step back 😕
The reason for this feature allows for you to customise it if you wanted to, but even with setting

If anything you can just Overwrite the existing Useragent that WE provide with one and this should work.
However I suspect that this isn't a "perfect" fix and will only work temporarily.

**Comment by joser93** [comment]
Thanks for the reply, but I didn't get the reason, the idea is to customize the user agent because it's allowed to do that, allows another feature to work, gives long term support without building a new version when is needed to change it or something else?

Anyway, i get that this is a feature that some people are interested about, but, should be a default user agent on first start or can be an option to allow in the settings that you can toggle and change it? the goal here is the main issue is solve, allow sign in with 2FA users and fixes a bug that some users might not use the app because of this. 

A decision should be made in the greater good for everyone or the majority and keep the development of the app, in my humble opinion.

If there's any feature that I must test without user agent, please, let me know.

**Comment by fimion** [comment]
As a side note: using 1.14.2 on Macos 13.5 and setting the user-agent to `null` in the config.json file does seem to  fix this issue.

Another thing i noticed too is that the back arrow on the login page was centered vertically when the login worked, but was always in the upper left hand corner when the login didn't work.

**Comment by Alipoodle** [comment]
Closing this PR in the move to YTMD v2

**Pull request closed without merging**
